import WhatsAppButton from "./components/WhatsAppButton";
import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head"; // Importar Head de Next.js

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {" "}
        {/* Usar el componente Head aquí */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css"
          integrity="sha512-oW2pDQk5hO5GHXM6E6B4FR5WR/qM8tP0gb27Aph6n+p8zkj9M4odbrI4Q10Uqg4A7vmWsxFowMEHqQ71x3Pe3w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <WhatsAppButton /> {/* Aquí se inserta el botón de WhatsApp */}
      </body>
    </html>
  );
}
